//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationISE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutomationISE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Azure AD Authentication Result is needed to query Azure for subscriptions..
        /// </summary>
        internal static string AzureADAuthResult {
            get {
                return ResourceManager.GetString("AzureADAuthResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cancelled sign-in..
        /// </summary>
        internal static string CancelSignIn {
            get {
                return ResourceManager.GetString("CancelSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found automation accounts.
        /// </summary>
        internal static string FoundAutomationAccounts {
            get {
                return ResourceManager.GetString("FoundAutomationAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found subscriptions.
        /// </summary>
        internal static string FoundSubscriptions {
            get {
                return ResourceManager.GetString("FoundSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local configuration file not found.
        /// </summary>
        internal static string LocalConfigurationFileNotFound {
            get {
                return ResourceManager.GetString("LocalConfigurationFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No automation accounts found in this subscription. Please create one in the Azure portal..
        /// </summary>
        internal static string NoAutomationAccounts {
            get {
                return ResourceManager.GetString("NoAutomationAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subscriptions found for this user account. Please create one in the Azure portal..
        /// </summary>
        internal static string NoSubscriptions {
            get {
                return ResourceManager.GetString("NoSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving automation accounts. Please wait....
        /// </summary>
        internal static string RetrieveAutomationAccounts {
            get {
                return ResourceManager.GetString("RetrieveAutomationAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving subscriptions for this user account. Please wait....
        /// </summary>
        internal static string RetrieveSubscriptions {
            get {
                return ResourceManager.GetString("RetrieveSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get Automation Accounts until an Azure subscription has been set..
        /// </summary>
        internal static string SubscriptionNotSet {
            get {
                return ResourceManager.GetString("SubscriptionNotSet", resourceCulture);
            }
        }
    }
}
